# url of website. format like http://<domain>/<path> or https://<domain>
url:

# website template
template: ccc45

# plugins, npm modules or script file name
plugins:
  - script.js
  # - xxx module

# output, where static site files located
public: /

# timezone, website timezone. use machine setting by default
# example: `America/New_York`, `Japan`, `UTC`, or `Asia/Shanghai`
timezone:

# language of website
language: en
